/**
 * Legacy URL map for the cutover from the previous static site.
 *
 * Lives here rather than in a host config file so it survives a change of
 * host: Astro emits these into whatever the adapter produces. Every target
 * was verified to exist before the rule was written.
 *
 * The old site answered on both the extensionless and the .html form
 * (pretty_urls was on), so both are mapped.
 */
/**
 * The JSDoc type is load-bearing: without it TypeScript widens `status: 301`
 * to `number`, which Astro's RedirectConfig rejects, and `npm run check`
 * fails while `astro build` still succeeds.
 *
 * @type {Record<string, { status: 301, destination: string }>}
 */
export const LEGACY_REDIRECTS = {
  "/case-machinery-erp": { status: 301, destination: "/work/manufacturing-erp-predictive-maintenance" },
  "/work-brightlane-garages": { status: 301, destination: "/work/brightlane-auto-group-garagezone" },
  "/case-fintech-support-copilot": { status: 301, destination: "/work/fintech-support-assistant" },
  "/case-dtc-shopify-rebuild": { status: 301, destination: "/work/dtc-shopify-rebuild" },
  "/case-manufacturing-attendance": { status: 301, destination: "/work/manufacturing-attendance-opsdeck" },
  "/insights": { status: 301, destination: "/blog" },
  "/solutions": { status: 301, destination: "/services" },
  "/attendance-management-system": { status: 301, destination: "/products/opsdeck" },
  "/garage-management-system": { status: 301, destination: "/products/garagezone" },
  "/lms-testing-platform": { status: 301, destination: "/products/loopiq" },
  "/industries-manufacturing": { status: 301, destination: "/industry/manufacturing" },
  "/industries-automotive": { status: 301, destination: "/industry/automotive" },
  "/industries-training-providers": { status: 301, destination: "/industry/corporate-training" },
  "/webflow-seo-day-one": { status: 301, destination: "/blog/webflow-seo-day-one" },
  "/metrics-ai-copilot-working": { status: 301, destination: "/blog/metrics-ai-copilot-working" },
  "/ship-ai-agent-production": { status: 301, destination: "/blog/ship-ai-agent-production" },
  "/reduce-payroll-errors-attendance": { status: 301, destination: "/blog/reduce-payroll-errors-attendance" },
  "/managed-software-retainer-guide": { status: 301, destination: "/blog/managed-software-retainer-guide" },
  "/what-is-a-managed-software-retainer": { status: 301, destination: "/blog/managed-software-retainer-guide" },
  "/ai-agents-copilots": { status: 301, destination: "/ai-and-emerging-technologies" },
  "/what-is-an-ai-agent": { status: 301, destination: "/ai-and-emerging-technologies" },
  "/what-is-an-ai-copilot": { status: 301, destination: "/ai-and-emerging-technologies" },
  "/build-vs-buy-ai": { status: 301, destination: "/ai-and-emerging-technologies" },
  "/responsible-ai": { status: 301, destination: "/trust-center" },
  "/security": { status: 301, destination: "/trust-center" },
  "/hire-dedicated-team": { status: 301, destination: "/hire" },
  "/websites-and-stores": { status: 301, destination: "/ecommerce-development" },
  "/webflow-cms-guide": { status: 301, destination: "/hire-webflow-developers" },
  "/webflow-vs-shopify": { status: 301, destination: "/ecommerce-development" },
  "/webflow-vs-wordpress": { status: 301, destination: "/custom-web-development" },
  "/customers": { status: 301, destination: "/work" },
  "/how-we-work": { status: 301, destination: "/about" },
  "/we-run": { status: 301, destination: "/application-maintenance" },
  "/partners": { status: 301, destination: "/technologies" },
  "/product-tour": { status: 301, destination: "/products" },
  "/comparisons": { status: 301, destination: "/work" },
  "/infoloop-vs-agency": { status: 301, destination: "/about" },
  "/infoloop-vs-in-house": { status: 301, destination: "/about" },
  "/resources": { status: 301, destination: "/blog" },
  "/resources-cto-checklist": { status: 301, destination: "/blog" },
  "/glossary": { status: 301, destination: "/blog" },
  "/ai-readiness-checklist": { status: 301, destination: "/contact" },
  "/roi-calculator": { status: 301, destination: "/contact" },
  "/pricing": { status: 301, destination: "/contact" },
  "/thank-you": { status: 301, destination: "/contact" },
  "/style-guide": { status: 301, destination: "/brand-assets" },
  "/case-machinery-erp.html": { status: 301, destination: "/work/manufacturing-erp-predictive-maintenance" },
  "/work-brightlane-garages.html": { status: 301, destination: "/work/brightlane-auto-group-garagezone" },
  "/case-fintech-support-copilot.html": { status: 301, destination: "/work/fintech-support-assistant" },
  "/case-dtc-shopify-rebuild.html": { status: 301, destination: "/work/dtc-shopify-rebuild" },
  "/case-manufacturing-attendance.html": { status: 301, destination: "/work/manufacturing-attendance-opsdeck" },
  "/insights.html": { status: 301, destination: "/blog" },
  "/solutions.html": { status: 301, destination: "/services" },
  "/attendance-management-system.html": { status: 301, destination: "/products/opsdeck" },
  "/garage-management-system.html": { status: 301, destination: "/products/garagezone" },
  "/lms-testing-platform.html": { status: 301, destination: "/products/loopiq" },
  "/industries-manufacturing.html": { status: 301, destination: "/industry/manufacturing" },
  "/industries-automotive.html": { status: 301, destination: "/industry/automotive" },
  "/industries-training-providers.html": { status: 301, destination: "/industry/corporate-training" },
  "/webflow-seo-day-one.html": { status: 301, destination: "/blog/webflow-seo-day-one" },
  "/metrics-ai-copilot-working.html": { status: 301, destination: "/blog/metrics-ai-copilot-working" },
  "/ship-ai-agent-production.html": { status: 301, destination: "/blog/ship-ai-agent-production" },
  "/reduce-payroll-errors-attendance.html": { status: 301, destination: "/blog/reduce-payroll-errors-attendance" },
  "/managed-software-retainer-guide.html": { status: 301, destination: "/blog/managed-software-retainer-guide" },
  "/what-is-a-managed-software-retainer.html": { status: 301, destination: "/blog/managed-software-retainer-guide" },
  "/ai-agents-copilots.html": { status: 301, destination: "/ai-and-emerging-technologies" },
  "/what-is-an-ai-agent.html": { status: 301, destination: "/ai-and-emerging-technologies" },
  "/what-is-an-ai-copilot.html": { status: 301, destination: "/ai-and-emerging-technologies" },
  "/build-vs-buy-ai.html": { status: 301, destination: "/ai-and-emerging-technologies" },
  "/responsible-ai.html": { status: 301, destination: "/trust-center" },
  "/security.html": { status: 301, destination: "/trust-center" },
  "/hire-dedicated-team.html": { status: 301, destination: "/hire" },
  "/websites-and-stores.html": { status: 301, destination: "/ecommerce-development" },
  "/webflow-cms-guide.html": { status: 301, destination: "/hire-webflow-developers" },
  "/webflow-vs-shopify.html": { status: 301, destination: "/ecommerce-development" },
  "/webflow-vs-wordpress.html": { status: 301, destination: "/custom-web-development" },
  "/customers.html": { status: 301, destination: "/work" },
  "/how-we-work.html": { status: 301, destination: "/about" },
  "/we-run.html": { status: 301, destination: "/application-maintenance" },
  "/partners.html": { status: 301, destination: "/technologies" },
  "/product-tour.html": { status: 301, destination: "/products" },
  "/comparisons.html": { status: 301, destination: "/work" },
  "/infoloop-vs-agency.html": { status: 301, destination: "/about" },
  "/infoloop-vs-in-house.html": { status: 301, destination: "/about" },
  "/resources.html": { status: 301, destination: "/blog" },
  "/resources-cto-checklist.html": { status: 301, destination: "/blog" },
  "/glossary.html": { status: 301, destination: "/blog" },
  "/ai-readiness-checklist.html": { status: 301, destination: "/contact" },
  "/roi-calculator.html": { status: 301, destination: "/contact" },
  "/pricing.html": { status: 301, destination: "/contact" },
  "/thank-you.html": { status: 301, destination: "/contact" },
  "/style-guide.html": { status: 301, destination: "/brand-assets" },
};
